language: python

python:
  - "3.5"

install:
  - sudo apt-get install pandoc
  - pip install -r requirements.txt
  - pip install sphinx nbsphinx
  - pip install -e .

build:
  - make docs

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  github-token: $GITHUB_TOKEN
  local-dir: docs/_build/html
  committer-from-gh: true
