name: black_and_lint
on: push
  jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - run: pip install black
      - run: black --check .
      - run: |
        python -m pip install --upgrade pip
        pip install pylint
      - name: Pylint
        run: pylint --rcfile=.pylintrc --extension-pkg-whitelist=numpy skmine/
